"""
Django settings for xtractme project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file (optional)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # dotenv not installed, skip loading .env file
    pass


def get_fix_unload_policy_script_url(request):
    """Returns the static URL for the unload policy fix script"""
    return staticfiles_storage.url("admin/js/fix_unload_policy.js")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-nep*=!xf(m5044#_!vb7vyv0wqj&71-+az&45eybhz^_h^f^c0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  # UnfoldAdmin theme - must be before django.contrib.admin
    'unfold.contrib.filters',  # Optional: Enhanced filters for UnfoldAdmin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'chat.apps.ChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xtractme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],  # Add core templates directory first to override UnfoldAdmin templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xtractme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,  # Wait up to 20 seconds for database to be available
        },
        'CONN_MAX_AGE': 0,  # Don't persist connections (helps with SQLite locking)
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# DeepSeek OCR Configuration
DEEPSEEK_OCR_ENABLED = True
# Use Ollama for DeepSeek OCR (if True, uses Ollama instead of separate API server)
# Set to True to use Ollama, False to use separate API server
DEEPSEEK_OCR_USE_OLLAMA = os.getenv('DEEPSEEK_OCR_USE_OLLAMA', 'True').lower() == 'true'
DEEPSEEK_OCR_API_URL = os.getenv('DEEPSEEK_OCR_API_URL', 'http://localhost:8001')
# Only used if DEEPSEEK_OCR_USE_OLLAMA is False
# Default to False if Ollama is enabled, otherwise check env var (default True for backward compat)
if DEEPSEEK_OCR_USE_OLLAMA:
    DEEPSEEK_OCR_USE_API = False
else:
    DEEPSEEK_OCR_USE_API = os.getenv('DEEPSEEK_OCR_USE_API', 'True').lower() == 'true'

# Tesseract OCR Configuration
# Set TESSERACT_CMD in .env file if Tesseract is not in PATH
TESSERACT_CMD = os.getenv('TESSERACT_CMD', None)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Ollama Configuration (for LLM integration)
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen3:4b')  # Default model name
OLLAMA_HOST = os.getenv('OLLAMA_HOST', 'http://localhost:11434')  # Ollama server URL

# UnfoldAdmin Configuration
UNFOLD = {
    "SITE_TITLE": "XtractMe",
    "SITE_HEADER": "XtractMe",
    "SITE_URL": "/",
    "SITE_SYMBOL": "description",  # Icon symbol for the sidebar
    "SHOW_HISTORY": True,  # Show history button
    "SHOW_VIEW_ON_SITE": True,  # Show view on site button
    # Fix for Permissions Policy violation: unload event not allowed
    # This script intercepts 'unload' event listeners and converts them to 'pagehide'
    # Using a callable to properly resolve the static file URL
    "SCRIPTS": [
        get_fix_unload_policy_script_url,
    ],
    # Sidebar navigation with icons
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Authentication and Authorization"),
                "separator": True,
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Core"),
                "separator": True,
                "items": [
                    {
                        "title": _("Documents"),
                        "icon": "article",
                        "link": reverse_lazy("admin:core_document_changelist"),
                    },
                    {
                        "title": _("Pages"),
                        "icon": "insert_drive_file",
                        "link": reverse_lazy("admin:core_page_changelist"),
                    },
                    {
                        "title": _("Prompts"),
                        "icon": "psychology",
                        "link": reverse_lazy("admin:core_prompt_changelist"),
                    },
                    {
                        "title": _("Schemas"),
                        "icon": "code",
                        "link": reverse_lazy("admin:core_schema_changelist"),
                    },
                    {
                        "title": _("Settings"),
                        "icon": "tune",
                        "link": reverse_lazy("admin:core_settings_changelist"),
                    },
                ],
            },
        ],
    },
}