# Generated by Django 6.0 on 2025-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ocr_engine',
            field=models.CharField(default='mineru', max_length=50),
        ),
    ]
