# Generated by Django 6.0 on 2025-12-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_ocr_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='json_data',
            field=models.JSONField(blank=True, help_text='Structured JSON data from MinerU', null=True),
        ),
    ]
