# Generated by Django 6.0 on 2025-12-24 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_json_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier for the prompt (e.g., 'document_summary')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Display name for the prompt', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this prompt does')),
                ('category', models.CharField(choices=[('document', 'Document'), ('page', 'Page'), ('structured', 'Structured Data'), ('custom', 'Custom')], default='document', help_text='Category of the prompt', max_length=50)),
                ('template', models.TextField(help_text='Prompt template with {variables} for formatting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this prompt is active and available for use')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default prompt for its category')),
                ('variables', models.JSONField(blank=True, default=list, help_text="List of variable names used in the template (e.g., ['document_title', 'document_content'])")),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this prompt has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['name'], name='core_prompt_name_7ede03_idx'), models.Index(fields=['category', 'is_active'], name='core_prompt_categor_a9e325_idx')],
            },
        ),
    ]
