# Generated by Django 6.0 on 2025-12-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier for the schema (e.g., 'invoice_schema')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Display name for the schema', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this schema is used for')),
                ('category', models.CharField(choices=[('document', 'Document'), ('page', 'Page'), ('structured', 'Structured Data'), ('extraction', 'Data Extraction'), ('validation', 'Validation'), ('custom', 'Custom')], default='structured', help_text='Category of the schema', max_length=50)),
                ('schema', models.JSONField(help_text='JSON schema definition (JSON Schema format)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schema is active and available for use')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default schema for its category')),
                ('properties', models.JSONField(blank=True, default=list, help_text="List of property names extracted from the schema (e.g., ['invoice_number', 'total_amount'])")),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this schema has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this schema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['name'], name='core_schema_name_318b43_idx'), models.Index(fields=['category', 'is_active'], name='core_schema_categor_807007_idx')],
            },
        ),
    ]
