"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.contrib.staticfiles.storage import staticfiles_storage

# Load environment variables from .env file
load_dotenv()


def get_fix_unload_policy_script_url(request):
    """Returns the static URL for the unload policy fix script"""
    return staticfiles_storage.url("admin/js/fix_unload_policy.js")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-nep*=!xf(m5044#_!vb7vyv0wqj&71-+az&45eybhz^_h^f^c0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  # UnfoldAdmin theme - must be before django.contrib.admin
    'unfold.contrib.filters',  # Optional: Enhanced filters for UnfoldAdmin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'chat.apps.ChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],  # Add core templates directory first to override UnfoldAdmin templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# DeepSeek OCR Configuration
DEEPSEEK_OCR_ENABLED = True
DEEPSEEK_OCR_API_URL = os.getenv('DEEPSEEK_OCR_API_URL', 'http://localhost:8001')
DEEPSEEK_OCR_USE_API = os.getenv('DEEPSEEK_OCR_USE_API', 'True').lower() == 'true'

# OLMOCR Configuration
OLMOCR_ENABLED = os.getenv('OLMOCR_ENABLED', 'True').lower() == 'true'
OLMOCR_API_URL = os.getenv('OLMOCR_API_URL', 'https://api.olmocr.com')
OLMOCR_USE_API = os.getenv('OLMOCR_USE_API', 'False').lower() == 'true'  # Default to local installation

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Ollama Configuration (for LLM integration)
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen3:4b')  # Default model name
OLLAMA_HOST = os.getenv('OLLAMA_HOST', 'http://localhost:11434')  # Ollama server URL

# UnfoldAdmin Configuration
UNFOLD = {
    "SITE_TITLE": "Document OCR Admin",
    "SITE_HEADER": "Document OCR Management",
    "SITE_URL": "/",
    "SITE_SYMBOL": "description",  # Icon symbol for the sidebar
    "SHOW_HISTORY": True,  # Show history button
    "SHOW_VIEW_ON_SITE": True,  # Show view on site button
    # Fix for Permissions Policy violation: unload event not allowed
    # This script intercepts 'unload' event listeners and converts them to 'pagehide'
    # Using a callable to properly resolve the static file URL
    "SCRIPTS": [
        get_fix_unload_policy_script_url,
    ],
}